CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR(20),
    BALANCE DECIMAL(15,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID INT,
    TRANSACTION_TYPE VARCHAR(20),
    AMOUNT DECIMAL(15,2),
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
);

CREATE TABLE ACCOUNT_AUDIT (
    AUDIT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID INT,
    OLD_BALANCE DECIMAL(15,2),
    NEW_BALANCE DECIMAL(15,2),
    CHANGE_DATE TIMESTAMP
);
