CREATE OR REPLACE PROCEDURE TRANSFER_FUNDS (
    IN P_FROM_ACCOUNT INT,
    IN P_TO_ACCOUNT INT,
    IN P_AMOUNT DECIMAL(15,2)
)
LANGUAGE SQL
BEGIN
    DECLARE V_BALANCE DECIMAL(15,2);

    SELECT BALANCE INTO V_BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = P_FROM_ACCOUNT;

    IF V_BALANCE < P_AMOUNT THEN
        SIGNAL SQLSTATE '75000'
        SET MESSAGE_TEXT = 'Insufficient Balance';
    END IF;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - P_AMOUNT
    WHERE ACCOUNT_ID = P_FROM_ACCOUNT;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + P_AMOUNT
    WHERE ACCOUNT_ID = P_TO_ACCOUNT;
END;
