CREATE OR REPLACE TRIGGER TRG_ACCOUNT_AUDIT
AFTER UPDATE ON ACCOUNTS
REFERENCING NEW AS N OLD AS O
FOR EACH ROW
WHEN (N.BALANCE <> O.BALANCE)
BEGIN ATOMIC
    INSERT INTO ACCOUNT_AUDIT
    (ACCOUNT_ID, OLD_BALANCE, NEW_BALANCE, CHANGE_DATE)
    VALUES
    (O.ACCOUNT_ID, O.BALANCE, N.BALANCE, CURRENT TIMESTAMP);
END;
