CREATE VIEW VW_CUSTOMER_SUMMARY AS
SELECT 
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    COUNT(A.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
    SUM(A.BALANCE) AS TOTAL_BALANCE
FROM CUSTOMERS C
LEFT JOIN ACCOUNTS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME;
