--Top 5 Customers by Transaction Value

SELECT 
    C.FIRST_NAME,
    C.LAST_NAME,
    SUM(T.AMOUNT) AS TOTAL_TRANSACTION_AMOUNT
FROM CUSTOMERS C
JOIN ACCOUNTS A ON C.CUSTOMER_ID = A.CUSTOMER_ID
JOIN TRANSACTIONS T ON A.ACCOUNT_ID = T.ACCOUNT_ID
GROUP BY C.FIRST_NAME, C.LAST_NAME
ORDER BY TOTAL_TRANSACTION_AMOUNT DESC
FETCH FIRST 5 ROWS ONLY;


--Monthly Transaction Summary

SELECT 
    YEAR(TRANSACTION_DATE) AS YEAR,
    MONTH(TRANSACTION_DATE) AS MONTH,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY YEAR(TRANSACTION_DATE), MONTH(TRANSACTION_DATE)
ORDER BY YEAR, MONTH;


--Inactive Accounts

SELECT A.ACCOUNT_ID
FROM ACCOUNTS A
LEFT JOIN TRANSACTIONS T
ON A.ACCOUNT_ID = T.ACCOUNT_ID
WHERE T.ACCOUNT_ID IS NULL;
